import { useEffect, useState } from 'react';
import { supabase } from './supabase';
import './styles.css';

// Set VITE_CUSTOMER_PORTAL_URL in Vercel to the current deployed portal address.
const portalUrl = import.meta.env.VITE_CUSTOMER_PORTAL_URL || 'https://alessandro-enterprises.vercel.app';
const fallbackContact = { email: 'alessandrosenterprises@gmail.com', phone: '+260 573 383 949', whatsapp: '260573383949' };
const route = () => location.pathname.split('/').filter(Boolean);
const money = (value) => Number(value) > 0 ? new Intl.NumberFormat('en-ZM', { style: 'currency', currency: 'ZMW' }).format(Number(value)) : null;

function SafeImage({ src, alt, className = '' }) {
  if (!src) return null;
  return <img className={className} src={src} alt={alt} onError={(event) => { event.currentTarget.style.display = 'none'; }} />;
}

export function App() {
  const [businesses, setBusinesses] = useState([]); const [services, setServices] = useState([]); const [products, setProducts] = useState([]); const [pages, setPages] = useState([]); const [posts, setPosts] = useState([]); const [contact, setContact] = useState(fallbackContact); const [current, setCurrent] = useState(route());
  const go = (path) => { history.pushState({}, '', path); setCurrent(route()); scrollTo({ top: 0, behavior: 'smooth' }); };
  useEffect(() => { const update = () => setCurrent(route()); addEventListener('popstate', update); return () => removeEventListener('popstate', update); }, []);
  useEffect(() => { async function load() { const [b, s, p, pg, u, c] = await Promise.all([supabase.from('business_profiles').select('*').eq('active', true).neq('id', 'enterprise').order('sort_order'), supabase.from('services').select('*').eq('active', true).is('deleted_at', null).order('name'), supabase.from('business_products').select('*').eq('active', true).order('name'), supabase.from('public_content_items').select('*').eq('published', true).order('created_at', { ascending: false }), supabase.from('content_posts').select('*').eq('published', true).order('created_at', { ascending: false }), supabase.from('website_content').select('key,value').eq('key', 'contact').maybeSingle()]); setBusinesses(b.data ?? []); setServices(s.data ?? []); setProducts(p.data ?? []); setPages(pg.data ?? []); setPosts(u.data ?? []); setContact({ ...fallbackContact, ...(c.data?.value ?? {}) }); } void load(); }, []);
  const section = current[0] || 'home';
  if (section === 'business' && current[1]) return <BusinessPage id={current[1]} businesses={businesses} services={services} products={products} contact={contact} go={go} />;
  if (['about', 'articles', 'events', 'moments'].includes(section)) return <ContentPage section={section} businesses={businesses} pages={pages} go={go} />;
  return <><Header go={go} /><main><section className="hero"><div><p className="eyebrow">ALESSANDRO ENTERPRISES</p><h1>One group.<em>Many possibilities.</em></h1><p>Trusted services, practical products and community support - all under one premium brand.</p><div className="hero-actions"><button className="gold-button" onClick={() => document.getElementById('explore')?.scrollIntoView({ behavior: 'smooth' })}>Explore our businesses</button><a className="outline-button" href={portalUrl} target="_blank" rel="noreferrer">Customer portal</a></div></div><div className="hero-logo"><SafeImage src="/alessandro-enterprises-logo.png" alt="Alessandro Enterprises" /></div></section><section id="explore"><SectionTitle eyebrow="EXPLORE" title="Our businesses" text="Choose a business to see its gallery, products and services." /><div className="business-grid">{businesses.map((item) => <button className="business-card" key={item.id} onClick={() => go(`/business/${item.id}`)} style={{ '--accent': item.accent_color }}><SafeImage src={item.logo_path} alt="" /><div><h3>{item.name}</h3><p>{item.tagline || 'Discover what this business offers.'}</p><span>Explore business -&gt;</span></div></button>)}</div></section><section className="updates-section"><SectionTitle eyebrow="LATEST" title="News and updates" /><div className="update-grid">{posts.slice(0, 3).map((item) => <article key={item.id}><SafeImage src={item.image_url} alt="" /><div><h3>{item.title}</h3><p>{item.description}</p></div></article>)}{!posts.length && <p className="empty">Updates from Alessandro Enterprises will appear here.</p>}</div></section></main><Footer contact={contact} go={go} /></>;
}

function Header({ go }) { const [open, setOpen] = useState(false); const explore = () => { setOpen(false); go('/'); window.setTimeout(() => document.getElementById('explore')?.scrollIntoView({ behavior: 'smooth' }), 40); }; return <header className="site-header"><a className="brand" href="/" onClick={(event) => { event.preventDefault(); go('/'); }}><SafeImage src="/alessandro-enterprises-logo.png" alt="" /><b>ALESSANDRO</b></a><button className="mobile-nav-toggle" onClick={() => setOpen(!open)} aria-label="Open navigation">Menu</button><nav className={open ? 'mobile-open' : ''}><button onClick={() => { setOpen(false); go('/'); }}>Home</button><button onClick={explore}>Explore Businesses</button><button onClick={() => { setOpen(false); go('/about'); }}>About</button><button onClick={() => { setOpen(false); go('/articles'); }}>Articles</button><button onClick={() => { setOpen(false); go('/events'); }}>Events</button><a href="#contact" onClick={() => setOpen(false)}>Contact</a><a className="portal" href={portalUrl} target="_blank" rel="noreferrer">Customer portal</a></nav></header>; }

function BusinessPage({ id, businesses, services, products, contact, go }) { const [business, setBusiness] = useState(null); const [gallery, setGallery] = useState([]); useEffect(() => { setBusiness(businesses.find((item) => item.id === id) ?? null); void supabase.from('business_gallery').select('*').eq('business_profile_id', id).order('sort_order').then(({ data }) => setGallery(data ?? [])); }, [id, businesses]); if (!business) return <><Header go={go} /><main className="page-shell">Loading business...</main></>; const offered = services.filter((item) => item.business_profile_id === id); const items = products.filter((item) => item.business_profile_id === id); return <><Header go={go} /><main className="page-shell"><button className="back" onClick={() => go('/')}>← All businesses</button><section className="business-hero" style={{ '--accent': business.accent_color, backgroundImage: business.cover_image_url ? `linear-gradient(100deg,rgba(4,22,45,.92),rgba(4,22,45,.48)),url(${business.cover_image_url})` : undefined }}><div><SafeImage src={business.logo_path} alt="" /><p className="eyebrow">ALESSANDRO ENTERPRISES</p><h1>{business.name}</h1><p>{business.tagline || 'Professional products and services for every need.'}</p></div></section><section className="gallery-section"><h2>Business gallery</h2><div className="business-gallery">{gallery.map((image) => <button key={image.id} className="gallery-image"><SafeImage src={image.image_url} alt={image.caption || business.name} /><span>{image.caption}</span></button>)}{!gallery.length && <p className="empty">Images will be added soon.</p>}</div></section><Catalogue title="Products" eyebrow="CATALOGUE" rows={items} logo={business.logo_path} /><Catalogue title="Available services" eyebrow="SERVICES" rows={offered} logo={business.logo_path} services /></main><Footer contact={contact} go={go} /></>; }

function Catalogue({ title, eyebrow, rows, logo, services }) { return <section className="catalogue-section"><SectionTitle eyebrow={eyebrow} title={title} /><div className="catalogue-grid">{rows.map((item) => <article key={item.id}><SafeImage src={item.image_url || logo} alt="" /><div><h3>{item.name}</h3><p>{item.description}</p>{money(item.price) && <b>{money(item.price)}</b>}{services && <div className="card-actions"><a href={`${portalUrl}/products/${item.id}`} target="_blank" rel="noreferrer">View service</a><a href={`${portalUrl}/book`} target="_blank" rel="noreferrer">Book service</a></div>}</div></article>)}{!rows.length && <p className="empty">No {services ? 'services' : 'products'} published yet.</p>}</div></section>; }

function ContentPage({ section, businesses, pages, go }) { const type = section === 'articles' ? 'article' : section === 'events' ? 'event' : section === 'moments' ? 'moment' : 'about'; const rows = pages.filter((item) => item.content_type === type); return <><Header go={go} /><main className="page-shell"><button className="back" onClick={() => go('/')}>← Home</button><SectionTitle eyebrow="ALESSANDRO ENTERPRISES" title={section[0].toUpperCase() + section.slice(1)} />{rows.map((item) => <article className={`content-card${item.image_url ? '' : ' no-image'}`} key={item.id}><SafeImage src={item.image_url} alt="" /><div><h2>{item.title}</h2><p>{item.summary}</p>{(item.body || '').split('\n').map((line, index) => <p key={index}>{line}</p>)}</div></article>)}{!rows.length && <p className="empty">No published content yet.</p>}</main></>; }
function SectionTitle({ eyebrow, title, text }) { return <div className="section-title"><p className="eyebrow">{eyebrow}</p><h2>{title}</h2>{text && <p>{text}</p>}</div>; }
function Footer({ contact, go }) { const explore = () => { go('/'); window.setTimeout(() => document.getElementById('explore')?.scrollIntoView({ behavior: 'smooth' }), 40); }; return <footer id="contact"><div><b>ALESSANDRO ENTERPRISES</b><p>One group. Many possibilities.</p><small>Copyright {new Date().getFullYear()} Alessandro Enterprises. All rights reserved.</small></div><div><h3>Quick links</h3><button onClick={() => go('/')}>Home</button><button onClick={explore}>Explore businesses</button><a href={portalUrl} target="_blank" rel="noreferrer">Customer portal</a></div><div><h3>Contact</h3><a href={`mailto:${contact.email}`}>{contact.email}</a><a href="tel:+260573383949">+260 573 383 949</a><a href={`https://wa.me/${String(contact.whatsapp).replace(/\D/g, '').replace(/^0/, '260')}`}>WhatsApp</a></div><div><h3>Business hours</h3><p>Monday - Saturday<br />08:00 - 17:00</p></div></footer>; }
